---
- hosts: all
  become: true
  roles:
    - role: .
      nginx_server_list:
        - name: "{{ ansible_hostname }}"
          root: "/tmp"
          access_log: "/var/log/nginx/{{ ansible_hostname }}-server_access.log"
          location_list:
            - name: "/"
              autoindex: "on"
  
#   - name: Display all variables/facts known for a host
#     debug: var=hostvars[inventory_hostname]

